language: node_js
node_js:
  - 0.6

before_script:
  - "curl -o JsTestDriver-1.3.5.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.5.jar'"
  - "java -jar JsTestDriver-1.3.5.jar --config jsTestDriver.conf --port 9876 &"
  - "sleep 3"
  - "phantomjs tests/phantomjs-jstd.js &"
  - "sleep 3"

notifications:
  email: false